[versions]
agp = "8.12.0"
android-compileSdk = "36"
android-minSdk = "30"
android-targetSdk = "36"
adaptive = "1.3.0-alpha03"
androidx-activityCompose = "1.12.2"
androidx-lifecycle = "2.10.0-alpha07"
coil3 = "2.8.2"
compose-multiplatform = "1.10.0-rc02"
kotlin = "2.3.0"
kotlinxCollectionsImmutable = "0.4.0"
material3Version = "1.10.0-alpha05"
room_version = "2.8.4"
ksp = "2.3.4"
sqlite = "2.6.2"
ktor-bom = "3.3.3"
koin-bom = "4.1.1"
koin-annotations-bom = "2.3.1"
kotlinx-datetime = "0.7.1"
navigation = "1.0.0-alpha06"
materialKolor = "4.0.5"
config = "0.17.1"
kotlinx-coroutines = "1.10.2"
store = "5.1.0-alpha07"
kermit = "2.0.8"

[libraries]
androidx-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
androidx-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "adaptive" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
jetbrains-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3Version" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "coil3" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor = { module = "io.ktor:ktor-bom", version.ref = "ktor-bom" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koin-annotations-bom" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations-bom" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations-bom" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room_version" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room_version" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

navigation3-compose-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation" }
navigation3-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3",version.ref = "androidx-lifecycle" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
store = { module = "org.mobilenativefoundation.store:store5", version.ref = "store" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room_version" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "config" }